/*
 * Copyright (c) 2024 inunix3
 *
 * This file is licensed under the MIT License (see LICENSE.md).
 */

#include <raypong/audio.h>
#include <raypong/defs.h>

/* Large file with embedded audio files, generated by CMake */
#include <embed/raypong.h>

#include <raylib.h>

#include <stddef.h>

static Sound sound_table[3];

void audio_init(void) {
    InitAudioDevice();
    SetMasterVolume(AUDIO_VOLUME);

    Wave wall_hit_raw = LoadWaveFromMemory(".wav", ef_wall_hit, ARRAY_SIZE(ef_goal));
    Wave paddle_hit_raw = LoadWaveFromMemory(".wav", ef_paddle_hit, ARRAY_SIZE(ef_goal));
    Wave goal_raw = LoadWaveFromMemory(".wav", ef_goal, ARRAY_SIZE(ef_goal));

    sound_table[SAMPLE_WALL_HIT] = LoadSoundFromWave(wall_hit_raw);
    sound_table[SAMPLE_PADDLE_HIT] = LoadSoundFromWave(paddle_hit_raw);
    sound_table[SAMPLE_GOAL] = LoadSoundFromWave(goal_raw);

    UnloadWave(wall_hit_raw);
    UnloadWave(paddle_hit_raw);
    UnloadWave(goal_raw);
}

void audio_deinit(void) {
    for (size_t i = 0; i < ARRAY_SIZE(sound_table); ++i) {
        UnloadSound(sound_table[i]);
    }

    CloseAudioDevice();
}

void audio_play(SampleId_t id) {
    PlaySound(sound_table[id]);
}
